from django.urls import path
from .views import (InSchoolPeopleList,
                    InSchoolPeopleCreate,
                    InSchoolPeopleUpdate,
                    InSchoolPeopleDelete,
                    OutSchoolPeopleList,
                    OutSchoolPeopleCreate,
                    OutSchoolPeopleUpdate,
                    OutSchoolPeopleDelete,
                    CourseList,
                    CourseCreate,
                    CourseUpdate,
                    CourseDelete,
                    AwardList,
                    AwardCreate,
                    AwardUpdate,
                    AwardDelete,
                    SectionList,
                    SectionCreate,
                    SectionUpdate,
                    SectionDelete,
                    SectionAttendingList,
                    SectionAttendingCreate,
                    SectionAttendingUpdate,
                    SectionAttendingDelete,
                    SQLQuery, )

urlpatterns = [
    path('', InSchoolPeopleList.as_view(), name='InSchoolPeopleList'),
    path('inSchool/', InSchoolPeopleList.as_view(), name='InSchoolPeopleList'),
    path('inSchool/create/', InSchoolPeopleCreate.as_view(), name='InSchoolPeopleCreate'),
    path('inSchool/update/<pk>/', InSchoolPeopleUpdate.as_view(), name='InSchoolPeopleUpdate'),
    path('inSchool/delete/<pk>/', InSchoolPeopleDelete.as_view(), name='InSchoolPeopleDelete'),
    path('outSchool/', OutSchoolPeopleList.as_view(), name='OutSchoolPeopleList'),
    path('outSchool/create/', OutSchoolPeopleCreate.as_view(), name='OutSchoolPeopleCreate'),
    path('outSchool/update/<pk>/', OutSchoolPeopleUpdate.as_view(), name='OutSchoolPeopleUpdate'),
    path('outSchool/delete/<pk>/', OutSchoolPeopleDelete.as_view(), name='OutSchoolPeopleDelete'),
    path('course/', CourseList.as_view(), name='CourseList'),
    path('course/create/', CourseCreate.as_view(), name='CourseCreate'),
    path('course/update/<pk>/', CourseUpdate.as_view(), name='CourseUpdate'),
    path('course/delete/<pk>/', CourseDelete.as_view(), name='CourseDelete'),
    path('award/', AwardList.as_view(), name='AwardList'),
    path('award/create/', AwardCreate.as_view(), name='AwardCreate'),
    path('award/update/<pk>/', AwardUpdate.as_view(), name='AwardUpdate'),
    path('award/delete/<pk>/', AwardDelete.as_view(), name='AwardDelete'),
    path('section/', SectionList.as_view(), name='SectionList'),
    path('section/create/', SectionCreate.as_view(), name='SectionCreate'),
    path('section/update/<pk>/', SectionUpdate.as_view(), name='SectionUpdate'),
    path('section/delete/<pk>/', SectionDelete.as_view(), name='SectionDelete'),
    path('attend/', SectionAttendingList.as_view(), name='AttendList'),
    path('attend/create/', SectionAttendingCreate.as_view(), name='AttendCreate'),
    path('attend/update/<pk>/', SectionAttendingUpdate.as_view(), name='AttendUpdate'),
    path('attend/delete/<pk>/', SectionAttendingDelete.as_view(), name='AttendDelete'),
    path('query/', SQLQuery.as_view(), name='SQLQuery'),
]
